<?php

namespace ContainerL2OfwPn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xu0ZQ4H.App\Entity\Address' shared service.
     *
     * @return \App\Entity\Address
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xu0ZQ4H": it needs an instance of "App\\Entity\\Address" but this type has been excluded in "config/services.yaml".');
    }
}
