<?php

namespace ContainerXwZRL63;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHgFFscService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CHgFFsc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CHgFFsc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'collectionRepo' => ['privates', 'App\\Repository\\CollectionRepository', 'getCollectionRepositoryService', true],
            'pageRepo' => ['privates', 'App\\Repository\\PageRepository', 'getPageRepositoryService', true],
            'settingRepo' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService', true],
            'slidersRepo' => ['privates', 'App\\Repository\\SlidersRepository', 'getSlidersRepositoryService', true],
        ], [
            'categoryRepo' => 'App\\Repository\\CategoryRepository',
            'collectionRepo' => 'App\\Repository\\CollectionRepository',
            'pageRepo' => 'App\\Repository\\PageRepository',
            'settingRepo' => 'App\\Repository\\SettingRepository',
            'slidersRepo' => 'App\\Repository\\SlidersRepository',
        ]);
    }
}
