<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2OfwPn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2OfwPn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL2OfwPn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL2OfwPn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL2OfwPn\App_KernelDevDebugContainer([
    'container.build_hash' => 'L2OfwPn',
    'container.build_id' => '3b02591c',
    'container.build_time' => 1713557527,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2OfwPn');
